server:
  port: 8080
spring:
  pplication:
    name: demo
  datasource:
    url: jdbc:mysql://access.cimevue.me:3309/access_face?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: cimevue@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate.use-new-id-generator-mappings: false
  #      hibernate.format_sql: true


